### ISSUE TITLE
Peer dependency

### ISSUE THREAD

**Issue by katp4** [nestjs/cqrs#1]
Hello,

I'm going through the tutorial on your website and I'm trying to run "npm install" after i cloned thenest-typescript-starter.

Just wanted to let you know of the below warnings and unmet peer dependency.
├─┬ UNMET PEER DEPENDENCY rxjs@5.4.2
npm WARN @nestjs/microservices@3.0.1 requires a peer of rxjs@5.0.3 but none was installed.
npm WARN @nestjs/core@3.0.1 requires a peer of rxjs@5.0.3 but none was installed.
npm WARN @nestjs/websockets@3.0.0 requires a peer of rxjs@5.0.3 but none was installed.

Thanks

**Comment by kamilmysliwiec** [comment]
Hi @katp4,
Thanks! The issue is obsolete after latest releases.
