### ISSUE TITLE
Configurable Event Bus support

### ISSUE THREAD

**Issue by reypader** [nestjs/cqrs#10]
I was wondering how the team envisioned a configurable event bus that can delegate to an external pub/sub and queueing mechanism like AMQP, Amazon SQS/SNS, Google Cloud Pub/Sub (I believe it's queued internally).

I was planning to just extend the event bus and override certain methods. However, I believe if we can instead allow injection of a publisher/subscriber in the event bus, it would allow users to do as they please on the event handling.

```
export class EventBus extends ObservableBus<IEvent> implements IEventBus {
    publish<T extends IEvent>(event: T) {
            if(this.eventPublisher){
                ...publish to external queue...
            } else {
                this.subject$.next(event);
            }
    }

    bind<T extends IEvent>(handler: IEventHandler<IEvent>, name: string) {
            const stream$ = name ? this.ofEventName(name) : this.subject$;
            stream$.subscribe(event => handler.handle(event));
            
            if(this.eventSubscriber){
                ...subscribe a worker to the external queue...
                ...once a message is consumed call "this.subject$.next(event);"...
            }
    }
}
```

Instead of the clunky if-else blocks, we can have a "DefaultPublisher" and "DefaultSubscriber" that immediately consumes a published messaged and thus, immediately triggering `this.subject$.next(event)` similar to how it is right now.

Any thoughts?

**Comment by reypader** [comment]
It could be worth changing the spec of the EventBus interface to instead have the `bind<T extends IEvent>(handler: IEventHandler<IEvent>, name: string)` rather than the publish. It could be more concise to have the `publish<T extends IEvent>(event: T)` on a separate publisher interface being wired to the `EventPublisher` - it could the `EventPublisher` class itself.

That would make it clearer that the publisher is the one publishing the events and the `EventBus` is the one that dispatches incoming events to its proper handler.

**Comment by reypader** [comment]
I'm currently testing some changes for this on my fork but when I tried using it in the example, I'm getting the error `Error: Cannot find module 'multer'`. It's actually the first time I've tried using local typescript modules. Any tips on how you guys test this locally?

**Comment by kamilmysliwiec** [comment]
Let's track this feature in your pull request: https://github.com/nestjs/cqrs/pull/12
