### ISSUE TITLE
Naming inconsistency

### ISSUE THREAD

**Issue by lkostrowski** [nestjs/cqrs#103]
CQRS exposes 3 decorators and 3 interfaces. All of them are singular form, except one:

CommandHandler
ICommandHandler

QueryHandler
IQueryHandler

EventsHandler
IEventHandler

I think it should be EventHandler

Maybe you can change this during next breaking change release

**Comment by kamilmysliwiec** [comment]
The difference is that `@EventsHandler` allows you subscribing to **many** events

**Comment by lkostrowski** [comment]
Ok, didn't realize that.
