### ISSUE TITLE
Middleware chain for command and querybud

### ISSUE THREAD

**Issue by JonasWijne** [nestjs/cqrs#1032]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have a issue when i want to log all commands, lets say I have a few commands and I want to log all commands that are run for auditing.

### Describe the solution you'd like

a middleware chain that can be registered onto the command or query bus.

middleware class and decorator to register (maybe with filters)

middleware class should have a handle method (like a command handler or queryhandler) that has 2 arguments 
command/query and a next function

### Teachability, documentation, adoption, migration strategy

small example
```ts
@Middleware()
export class LogMiddleware implements IMiddleware<any, any> {
    handle(command: ICommand, next: NextFunction): any {
        console.log(command);
        return next(command);
    }
}
```

### What is the motivation / use case for changing the behavior?

this allows for adding functionality without changing behaviour.

**Comment by FredericEspiau** [comment]
For your information, you can already do it using the ExplorerService: https://github.com/nestjs/cqrs/blob/master/src/services/explorer.service.ts
