### ISSUE TITLE
Does the CQRS implement the Transactional outbox Pattern as well?

### ISSUE THREAD

**Issue by UmerIftikhar** [nestjs/cqrs#113]
As per the [Transactional outbox Pattern](https://microservices.io/patterns/data/transactional-outbox.html) the database update and sending of the message must be atomic in order to avoid data inconsistencies and bugs.
There might be a case where event bus might be down or database transaction (local one) fails. right?

Does this module tackle and solve this problem by using the OUTBOX table and by mining the Transaction Log?

**Comment by BennoDev** [comment]
No it does not, this module only enables developers to apply the CQRS pattern at an application level, not infrastructural level.

An implementation of that pattern goes far beyond the scope of this module, and nest in general.
