### ISSUE TITLE
Event handler not working in the unit test?

### ISSUE THREAD

**Issue by murbanowicz** [nestjs/cqrs#119]
I came across really strange issue.
I described it in Discord but I think I haven't miss anything (but still probably have...) and it looks like some strange issue with Nest or maybe just docs?

I have command which is creating the Tenant. It is emiting the event TenantCreated.  In memberships, event handler listening to this event and creating admin role for user which created the tenant.
I had it async but figure out this one should be exception and I should wait until MembershipCreated for this Tenant id and user id is emmited so as soon as user will get the response, he will be for sure assigned to the tenant as admin.

This is my command handler (some parts omitted)
![image](https://user-images.githubusercontent.com/9385106/63619423-e8cabd80-c5ee-11e9-939b-e58a0e353f24.png)

This is my TenantCreated handler:
![image](https://user-images.githubusercontent.com/9385106/63619443-f3855280-c5ee-11e9-9b9f-98d214f84c08.png)

This is how I do the test initialization:
![image](https://user-images.githubusercontent.com/9385106/63619464-ff711480-c5ee-11e9-85cf-25c87de9e9f1.png)

The test itself:
![image](https://user-images.githubusercontent.com/9385106/63619473-06982280-c5ef-11e9-8efc-27dbf53727b4.png)

and the issue is that it hangs... During this unit test, TenantCreated event never reaches the handler so command gets stuck... 
An interesting fact is that during E2E test with a full-blown app it is working like a charm without any issues...
I would be really thankful if someone would point the issue...

The event handler is visible in the providers so it should be registered (it gets created!) and receive the events (it does not), so I hope this is not my fault?

**Comment by kamilmysliwiec** [comment]
Could you please provide a minimal repository which reproduces your issue?:)

**Comment by bratello** [comment]
> @murbanowicz Did you resolve this issue? I have the same problem, from tests, my event handlers are not triggered...

Same issue. Did you get some progress? First I decided that some problem happens with async events. I checked with simple sync event - no matter sync or async, they are all seems to be ASSync.

**Comment by andynunes** [comment]
> @bratello @zveljkovic had a similar issue, which was fixed by calling `await module.init()` after building the testing module.

Thank you for sharing @Andrepav1 - this also fixed a similar issue for me but using the `@nestjs/event-emitter` package.

**Comment by DanielMenke** [comment]
@andynunes could you provide a working example? I am also having this problem with the `@nestjs/event-emitter package`. It is working fine if I create the complete AppModule as TestModule but fails if I only build a subset of its modules. 

this: 
`  const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();`
    
    VS. 
this:

` const module: TestingModule = await Test.createTestingModule({
      providers: [RecipesService, PrismaService, EventEmitter2],
    })
      .overrideProvider(PrismaService)
      .useValue(mockDeep<PrismaClient>())
      .compile();

    await module.createNestApplication();
    await module.init();`

**Comment by andynunes** [comment]
@DanielMenke Sure thing, however, my use case doesn't override providers. Hope it helps nonetheless:

In `beforeAll()`
```
        ...
        this.testingModule = await Test.createTestingModule({
            providers: [
               // only needed providers
            ],
            imports: [
                ConfigurationModule,
                ConfigModule.forRoot({
                    validate: EnvironmentVariables.validate,
                    isGlobal: true
                }),
                EventEmitterModule.forRoot(),
                // other imports
            ]
        }).compile();

        await this.testingModule.init();
        ...
```

**Comment by DanielMenke** [comment]
@andynunes 
The problem was that I put `EventEmitter2` in the providers AND imported the `EventEmitterModule.forRoot()`. Only the latter is necessary and gets overridden with an `EventEmitter2`-instance without any registered listeners as soon as I put the `EventEmitter2` inside the providers.

**Comment by andynunes** [comment]
Nice, glad to hear you found the issue!
