### ISSUE TITLE
Saga events - request context

### ISSUE THREAD

**Issue by justinpenguin45** [nestjs/cqrs#1195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Thank for providing this extension to the Nestjs framework, it's pretty cool. In the sample it's not apparent to me if the event stream provided for the sagas is request scoped. Hopefully it is, but it would be great if the documentation has some information about this, or that somehow the heroes/dragons sample demonstrated this. When using the event stream in the saga, it's very important to know if the events observable is scoped per request, or if you could get events that are spread across different requests. Of course this only matters when f.e. using combinators and merging two streams of different event types. I'm imagining a situation where, say maybe we reach out to asynchronous services (3rd party web API, database, etc). It would be bad if those asynchronous events could complete and join into the saga event stream in a different context than the original request it was spawned from. Hopefully this makes sense

### Minimum reproduction code

None

### Expected behavior

The documentation should state what the context is of the event stream in the saga - being that the saga is a singleton, it's not clear if the events stream is request scoped. The sample does not demonstrate or hint at what the steam context is either.

### Package version

8.1.3

### NestJS version

8.1.3

### Node.js version

14.17.6

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
