### ISSUE TITLE
documentation request

### ISSUE THREAD

**Issue by xenoterracide** [nestjs/cqrs#1208]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I don't feel the usage/api of `apply` is adequately documented.

the docs don't mention history at all https://docs.nestjs.com/recipes/cqrs there's no jsdoc https://github.com/nestjs/cqrs/blob/master/src/aggregate-root.ts#L42

there's already a loadFromHistory which is also not documented.

How is this supposed to be used? 

### Describe the solution you'd like

please add some kind of documentation around history and events that shouldn't be republished.

### What is the motivation / use case for changing the behavior?

I did ask this question on discord, hasn't seen any traction for several days. I imagine the discord is more where I could get answers from the developers than SO, which is likely to close this as it's asking something they would consider subjective or unanswerable. It's only answerable by a developer

> I have an event inbound from kafka, I want my aggregate to take action on this event, but it will already have been propagated through the event bus at this point, so I don't want to republish on commit. I know I can use the history boolean to prevent this, but that feels like I'm abusing it. Are we doing something other than intended? is there a better workflow?

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/cqrs/issues/598
