### ISSUE TITLE
problems constructing instance with Mikro ORM

### ISSUE THREAD

**Issue by xenoterracide** [nestjs/cqrs#1236]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

MikroORM by default doesn't use a classes constructor, and when you set it to it would appear to require it to be no args constructor making it harder to make your properties actually immutable. What's happening is that when you create a subclass of `AggregateRoot` the `INTERNAL_EVENTS` array isn't being instantiated, this is very frustrating. Made more frustrating by the fact that there appears to be (probably appropriately) no way to instantiate this variable from the outside.

### Describe the solution you'd like

Honestly not entirely certain if there is an appropriate way, you could just give it a setter...

Here is a yarn patch I wrote for our local implementation. Honestly I think the property could be protected and have a getter/setter though. Not sure why both aren't protected tbh. [@nestjs-cqrs-patch-18dae1d610-b77de7d8cf.zip](https://github.com/nestjs/cqrs/files/10469203/%40nestjs-cqrs-patch-18dae1d610-b77de7d8cf.zip)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
