### ISSUE TITLE
Feat: Register Commands, Queries & Events programatically

### ISSUE THREAD

**Issue by rjlopezdev** [nestjs/cqrs#1237]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We need to reuse code from other packages  not annotated with Nest decorators.

### Describe the solution you'd like

An hability to register commands, queries & events programatically from other package with no Nest decorators.

```typescript
@Module({
  imports: CqrsModule.forRoot({
    adapter: (executable, commandQueryEvent) => {
      return executable.myHandleMethod(commandQueryEvent);
    } // Apply for external command, queries & events
  })
})
export class AppModule {}
```

```typescript
@Module({
  imports: [
    CqrsModule.forFeature({
      queries: [
        { query: MyQuery, handler: MyQueryHandler, deps: [Dep1, Dep2] }
      ]
    })
  ],
  providers: [Dep1, Dep2],
})
class MyFeatureModule {}
```

**Alternative**
A `CQRSRegistry`.
```ts
...
constructor(private readonly cqrsRegistry: CQRSRegistry) {
  cqrsRegistry.registerQuery(MyQuery, (query) => new MyQueryHandler(...).handle(query));
  cqrsRegistry.registerCommand(MyCommand, (command) => new MyCommandHandler(...).handle(command));
  cqrsRegistry.registerEvent(MyEvent, (event) => new MyEventHandler(...).handle(event));
}
```

### What is the motivation / use case for changing the behavior?

In case we have a package `@my-domain/feature` that host this code:

```typescript
import { IQueryHandler } from '@my-domain/core';
import { MyQuery, MyQueryResult } from './my-query';
import { Dep1 } from '../services/dep1';
import { Dep2 } from '../services/dep2';

export class MyQueryHandler implements IQueryHandler<MyQuery, MyQueryResult> {

  constructor(
    private readonly dep1: Dep1,
    private readonly dep2: Dep2
  ) {}

  execute(query: MyQuery): Promise<MyQueryResult> {
    // Logic here
  }
}
```

I need to use it in a Nest context.
We do that for decoupling application layer of infraestructure (Nestjs API).

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
