### ISSUE TITLE
Multiple execution of events based on how many times module is imported

### ISSUE THREAD

**Issue by gentunian** [nestjs/cqrs#1318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

While using the `EventBus` to publish an event, the latest will be executed as many times as the module has been imported.

This does not happen with `CommandBus`.

### Minimum reproduction code

https://github.com/gentunian/nestjs-v7-multiple-events-fired

### Steps to reproduce

1. `git clone https://github.com/gentunian/nestjs-v7-multiple-events-fired`
2. `cd nestjs-v7-multiple-events-fired`
3. `npm i`
4. `npm run start`
5. In another terminal run: `curl http://localhost:3000/foo/bar`

### Expected behavior

Event `handle()` should have been called just once. As the same as a command `execute()` method.

### Package version

^7.0.1

### NestJS version

^7.6.15

### Node.js version

12.22.12

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
