### ISSUE TITLE
CQRS  module lack of support for hybrid microservice

### ISSUE THREAD

**Issue by Yanivox** [nestjs/cqrs#139]
## Current behavior
Hello,
I'm building a microservice that will support both TCP and RMQ connections,

If I use the regular microservice set up for my project the CQRS works great.
like so:

`  const microserviceOptions = {
    transport: Transport.RMQ,
    options: {
      queue: 'data',
      urls: ['amqp://localhost:5672'],
    },
  }
  
  const app = await NestFactory.createMicroservice(AppModule, microserviceOptions);
  app.listen(() => console.log("Microservice is listening"));`

but if change it to support hybrid application I get the 

>  CommandHandler not found exception!

`  const microserviceOptions = {
    transport: Transport.RMQ,
    options: {
      queue: 'data',
      urls: ['amqp://localhost:5672'],
    },
  };

  const app = await NestFactory.create(AppModule);
  app.connectMicroservice(microserviceOptions);
  app.startAllMicroservices(() => console.log('Microservice is listening'));`

## Environment

<pre><code>
Nest version: 6.0.0
 
For Tooling issues:
- Node version: 10.14.1
- Platform:  Mac

Others:
using VSCode
</code></pre>

**Comment by Yanivox** [comment]
https://github.com/Yanivox/nest-cqrs-example

**Comment by Yanivox** [comment]
I found the solution for this bug.
I'll make a pull request
![Screen Shot 2019-10-10 at 19 33 05](https://user-images.githubusercontent.com/1440203/66588341-ec150b00-eb94-11e9-8a97-e8e43dfc1655.png)

**Comment by kamilmysliwiec** [comment]
Let's track this issue here https://github.com/nestjs/nest/pull/3153

**Comment by Samox** [comment]
Can we re-open this issue? We use CQRS and we'd like hybrid applications (in order to add a `/healthcheck` endpoint on our microservice process). 
Here is a repository with the issue https://github.com/Samox/nestjs-microservices-example
