### ISSUE TITLE
Sagas stop working in case of exceptions

### ISSUE THREAD

**Issue by baikov-ilia** [nestjs/cqrs#1401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently UnhandledExceptionBus tirggers only once when exception is thrown from Command (for example) and there is no reaction on further exception. Same thing for `@Saga` actually as well

### Minimum reproduction code

https://github.com/baikov-ilia/nestjs-cqrs-issue-exceptions

### Steps to reproduce

1. `npm i`
2. `npm run start:dev`
3. Open `http://localhost:3000/`
4. First time you will see that `@Saga` executed with no issues (because first request is ignored and command not throwing any error)
5. Refresh page. You will see in logs that `UnhandledExceptionBus` logged error as expected.
6. Refresh page one more time. `@Saga` not going to trigger command. Even pipe operators not being executed.

 `@Saga` added for clarification of potential bug in CQRS realisation under the hood that leading to unusable CQRS features.

### Expected behavior

`@Saga`  should trigger on the same event and then run command. Any exception can be handled by developer. I tried to add `catchError` operator but doesn't give any effect. It feel like Saga is just crashed and no way to trigger without app restart.
### Package version

^10.0.1

### NestJS version

^10.0.0

### Node.js version

v16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

Also i discovered misinformation in docs that CommandHandlers can be used with `ExceptionFilters` but looks like it isn't working (https://docs.nestjs.com/recipes/cqrs#events)

**Comment by kodeine** [comment]
@baikov-ilia were you able to solve this? i am facing the same issue

**Comment by baikov-ilia** [comment]
> @baikov-ilia were you able to solve this? i am facing the same issue

Not really. I'm switched to approach to define command result to follow next schema:
```
{ status: "SUCCESS" | "FAILED", result: any }
```
and simply wrap command execution to try/catch. In case of failure simply return result with `success` or `failed` status.
Any other enterprise-like are leading to use Java (Axon).
