### ISSUE TITLE
Command handler becomes unresponsive

### ISSUE THREAD

**Issue by incompletude** [nestjs/cqrs#1428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The command handler becomes unresponsive if its execution was triggered by a saga and the handler throws an unhandled exception.

### Minimum reproduction code

[project-name.zip](https://github.com/nestjs/cqrs/files/12136916/project-name.zip)

### Steps to reproduce

`npm i` and `docker-compose up` and watch logs. The `TestEvent` is added to the `eventBus` twice, if the command handler throws an error, it becomes unresponsive and does not respond to the second event.

### Expected behavior

The command handler should respond normally.

### Package version

10

### NestJS version

10

### Node.js version

17 LTS
18 LTS

### In which operating systems have you tested?

macOS with Linux docker container, same error for node:17 and node:18.

### Other

Version 8.0.3 works fine in case someone needs.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/cqrs/pull/1430

**Comment by incompletude** [comment]
Still not working on 10.0.2. Now it crashes the app.

**Comment by intwone** [comment]
With 10.0.2 version:

![image](https://github.com/nestjs/cqrs/assets/42350844/94c3b397-85e5-405b-b85b-d8f2878d1a17)

**Comment by kamilmysliwiec** [comment]
Fixed in 10.0.3
