### ISSUE TITLE
Use a decorator to automatically merge event publisher into AggregateRoot

### ISSUE THREAD

**Issue by StimulCross** [nestjs/cqrs#1466]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The current design requires to merge the event publisher with an aggregate root, which produces some boilerplate code.

```ts
const UserModel = this.publisher.mergeClassContext(User);
const user = new UserModel({ id: 1, name: 'stimulcross' });
```

### Describe the solution you'd like

The case above can be implemented in a more declarative way - the `@Publishable()` decorator that has to be applied to an `AggregateRoot` class to automatically merge it with the event publisher.

`user.ts`
```ts
@Publishable()
export class User extends AggregateRoot {
  constructor(private readonly props: UserProps) {}

  static create(props: UserProps): User {
    const user = new User(props);
    user.apply(new UserCreatedEvent(props.id));
    return user;
  }
}
```

And this can be used somewhere else:
```ts
const user = User.create({ id: 1, name: 'stimulcross' });
// Persist user...
user.commit();
```

### Teachability, documentation, adoption, migration strategy

This is an alternative approach, so this won't produce a breaking change. 

People still can use the current approach to make their aggregates publishable. or they just can apply `@Publishable()` decorator on the aggregates and remove manual merging from their code.

### What is the motivation / use case for changing the behavior?

This solution brings a more declarative approach that fits well with NestJS philosophy and allows developers to focus on their business logic.

In my personal project, the repositories already return domain models (entities or aggregate roots), so this makes the code cleaner.

```ts
// Fetch user model
const user = await this._repository.getUserById(id);
// Make updates and apply required events internally
user.update(...);
// Persist the model
await this._repository.updateUser(user);
// Commit
user.commit();
```

I will link a PR for review. Probably, it's not production ready yet (I've tested it with `yalc`, though), but it clearly represents the concept.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/cqrs/pull/1467
