### ISSUE TITLE
App crashes if event handler triggers a command that throws

### ISSUE THREAD

**Issue by johanbook** [nestjs/cqrs#1485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If an event handler triggers a command which in turn throws an error, the app enters an unresponsive state and requires a restart. This is similar to https://github.com/nestjs/cqrs/issues/409 which seems to have be fixed. See bottom or attached repo for code example.

### Minimum reproduction code

https://github.com/johanbook/nest-event-handler-crash

### Steps to reproduce

Clone https://github.com/johanbook/nest-event-handler-crash and run

1. Run `npm i -D`
2. Run `npm start`
3. Go to [localhost:3000/docs](http://localhost:3000/docs)
4. Trigger `/error-directly` endpoint and see that the application handles the error.
5. Trigger `/error-through-event-handler` and see that the application crashes and cannot recover.

### Expected behavior

The app handles the error instead of becoming unresponsive, similar to how other errors are handled within an event handler.

### Package version

10.0.3

### NestJS version

10.1.2

### Node.js version

v20.5.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [x] Linux

### Other

Here is a code example for reference. Consider a command handler that triggers an event

```ts
import { CommandHandler, EventBus, ICommandHandler } from "@nestjs/cqrs";

import { TriggerEventCommand } from "../commands/trigger-event.command";
import { MyEvent } from "../events/event";

@CommandHandler(TriggerEventCommand)
export class TriggerEventCommandHandler
  implements ICommandHandler<TriggerEventCommandHandler, void>
{
  constructor(private readonly eventBus: EventBus) {}

  async execute() {
    const event = new MyEvent();
    this.eventBus.publish(event);
  }
}
```

and an event handler that triggers another command

```ts
import { CommandBus, EventsHandler, IEventHandler } from "@nestjs/cqrs";

import { FailureCommand } from "../commands/failure.command";
import { MyEvent } from "../events/event";

@EventsHandler(MyEvent)
export class MyEventHandler implements IEventHandler<MyEvent> {
  constructor(private readonly commandBus: CommandBus) {}

  handle() {
    const command = new FailureCommand();
    this.commandBus.execute(command);
  }
}
```

which is handled by handler that throw an error

```ts
import { CommandHandler, ICommandHandler } from "@nestjs/cqrs";

import { FailureCommand } from "../commands/failure.command";

@CommandHandler(FailureCommand)
export class FailureCommandHandler
  implements ICommandHandler<FailureCommand, void>
{
  async execute() {
    throw new Error("Triggered by FailureCommandHandler");
  }
}
```

**Comment by kamilmysliwiec** [comment]
`CommandBus#execute` returns a promise that you must await. Once you add `await`, your application will no longer crash due to unhandled promise rejections
