### ISSUE TITLE
'this' not available to event handlers in Types derived from AggregateRoot

### ISSUE THREAD

**Issue by adebisi-fa** [nestjs/cqrs#15]
Hello,

Thanks for this awesome ng-inspired library on 'express-js'.  It's rocks (and well-designed, too)!!!!

This following line refers, please:
https://github.com/nestjs/cqrs/blob/78635ed2e2439ea405542dcf1fe67bacbcb168fa/src/aggregate-root.ts#L33

### CURRENT LOGIC

With the current logic

```
handler && handler(event);
```
The 'this' context-variable represents the ```onEventTypeName()``` function INSTEAD of the ```AggregateRoot``` (or its derivative) instance.
```
. . .
name: string
. . . 
onEventTypeName(event: EventTypeName) {
   // 'this' here represents the function
  this.name = event.name; // it breaks, doesn't work.
}
```

### SUPPOSED/CORRECT LOGIC

But, with the following logic

```
handler && handler.call(this, event);
```
The 'this' context-variable represents the ```AggregateRoot``` (or its derivative) instance, as desired.
```
. . .
name: string;
. . .
onEventTypeName(event: EventTypeName) {
   // 'this' here represents the AggregateRoot (or its derivate), i.e. the parent of this function.
  //     Thus, is can access field/other members of the class
  this.name = event.name; // works
}
```

If the supposed logic is right, do you mind a pull request or you prefer to just fixed it up from your end?

**Comment by kamilmysliwiec** [comment]
Thanks @adebisi-fa! Fixed in `5.1.0`
