### ISSUE TITLE
Commit method throws an error when trying to publish domain events

### ISSUE THREAD

**Issue by ikovac** [nestjs/cqrs#1530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

commit method throws: "Cannot read properties of undefined (reading 'push')" error when trying to publish domain events.
Inside Movie entity I have `publishVersion` method which applies `MoviePublishedEvent`.

```ts
// Movie entity
import { Entity, Property } from '@mikro-orm/core';
import { BaseAggregateRoot } from 'shared/database/base.entity';
import { MoviePublishedEvent } from '../events/movie-published.event';

@Entity()
export class Movie extends BaseAggregateRoot {
  @Property()
  title: string;

  @Property()
  overview: string;

  @Property()
  imageUrl: string;

  @Property()
  year: number;

  constructor(title: string, overview: string, imageUrl: string, year: number) {
    super();
    this.title = title;
    this.overview = overview;
    this.imageUrl = imageUrl;
    this.year = year;
  }

  publishVersion() {
    this.apply(
      new MoviePublishedEvent(
        this.id,
        this.title,
        this.overview,
        this.imageUrl,
        this.year,
      ),
    );
  }
}
```

```ts
// Movie service publish method
async publish(movieId: number) {
    const entity = await this.repository.findOne(movieId);
    if (!entity) throw new Error('Movie does not exist');
    const movie = this.eventPublisher.mergeObjectContext(entity);
    movie.publishVersion();
    movie.commit();
  }
```

### Minimum reproduction code

https://github.com/ikovac/movie-theater/blob/master/apps/backend/src/authoring/application/use-cases/movie.service.ts#L30

### Steps to reproduce

1. cd into backend folder
2. start dev server `pnpm start:dev`
3. hit `/api/movies/:id/versions` route and try to publish movie version
4. error is thrown

### Expected behavior

`movie.commit` should publish an event and not throw an error.

### Package version

10.2.6

### NestJS version

10.0.0

### Node.js version

18.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
