### ISSUE TITLE
EventBus.publish() should return a Promise

### ISSUE THREAD

**Issue by sroze** [nestjs/cqrs#156]
## I'm submitting a...

[x] Feature request

## Current behavior

At the moment, the `publish` method of the `EventBus` does return `void`. When publishing an event, how can I make sure that all handlers have been executed? Without this, I'm at risk of having lost some messages. 

## Expected behavior

`EventBus` should return `Promise<void>`. `void` because we should not expect any return value.

**Others**

Do you have any objection against this? The promise would resolve when all handlers have been called.

**Comment by kamilmysliwiec** [comment]
The implementation is based on RxJS streams. `publish` method is intended to be loosely coupled from subscribers and doesn't track whether every `EventHandler` failed or not.

**Comment by sroze** [comment]
@kamilmysliwiec for systems where consistency is really important, it doesn't make sense not to have the ability to know whether or not the message has been received. 

> publish method is intended to be loosely coupled from subscribers

It it returns a `Promise` or a way to acknowledge the message has been successfully dispatched (i.e. actually stored in a message bus or, in the example of a synchronous event listener, actually handled) does not couple anything whatsoever, it just allows delivery guarantees.

**Comment by kamilmysliwiec** [comment]
@sroze please, note that this library is just a lightweight implementation based on RxJS. Systems vary by requirements and hence, for more sophisticated scenarios, this library should be forked and tailored to the technical expectations of the project (if needed). CQRS and event-based systems is a huge topic and it's pretty much impossible for us to cover every single use-case and provide all possibly useful functionalities out-of-the-box.
