### ISSUE TITLE
Patch update reflect-metadata

### ISSUE THREAD

**Issue by phpjob** [nestjs/cqrs#1578]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It looks like renovate is blocking patch updates for the package reflect-metadata, as it may already created a PR for a minor update? So it would be nice to patch update reflect-metadata from 0.1.13 to 0.1.14.

### Describe the solution you'd like

i created a [pr](https://github.com/nestjs/cqrs/pull/1572), which patch updates 0.1.14. I could not managed to run the tests locally, but maybe you have an idea?

### What is the motivation / use case for changing the behavior?

As other packages of nestjs already updated reflect-metadata from 0.1.13 to 0.1.14 we should maybe align with that.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/cqrs/pull/1572
