### ISSUE TITLE
Is there way to make CommandBus and QueueBus external? 

### ISSUE THREAD

**Issue by imissyouso** [nestjs/cqrs#179]
Is there way to make Command Bus and Queue bus external by using Kafka or RabbitMQ under the hood? Thanks.

**Comment by wadedos** [comment]
There is a way for events AFAIK, but not for querys and commands currently.

- Issue - https://github.com/nestjs/cqrs/issues/10
- PR - https://github.com/nestjs/cqrs/pull/12

**Comment by kamilmysliwiec** [comment]
In v7.0.0, we added a way to swap the underlying Pub & Sub mechanism for both queries and commands (similarly to what we had implemented already for events).

Let's track the progress on the tutorial here https://github.com/nestjs/docs.nestjs.com/issues/1239
