### ISSUE TITLE
Middleware Bus

### ISSUE THREAD

**Issue by ancyrweb** [nestjs/cqrs#1865]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It's very common for mediator implementations such as this one (examples: MediatR, PipelinR, Messenger) to allow clients to intercepts commands/queries and act upon them. This serves multiple needs : 

- Logging
- Transaction Wrapping
- Validation
- Serialization

Thus the Mediator implementation serves as the spine of the application so that all these concerns can be managed internally independently of the input source. Also a very common pattern in languages such as C#.

### Describe the solution you'd like

Add a middleware implementation for all three buses that allow clients to specify methods to be called when a command is dispatched. 
The call order is defined by the user and can probably be implemented the same way interceptors are implemented (using Observables).

### What is the motivation / use case for changing the behavior?

The motivation is described above.

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/recipes/cqrs#subscribing-to-all-events
