### ISSUE TITLE
Allow retrying on sagas

### ISSUE THREAD

**Issue by MartinAndreev** [nestjs/cqrs#1866]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We use the CQRS module a lot, but we encountered the following problem.

We have a database with a read/write replica and sometimes we have a replication lag, so we want to delay and retry the event processing with [rxjs Retry](https://rxjs.dev/api/operators/retry) but due to how the commands are handled, we cannot do that. 

### Describe the solution you'd like

A simple solution would be to allow passing a simple config to the CQRS module, which is later passed to 

```typescript
protected registerSaga(saga: ISaga<EventBase>) {
```

something like

```typescript
const subscription = stream$
      .pipe(
        filter((e) => !!e),
        mergeMap((command) =>
          defer(() => this.commandBus.execute(command)).pipe(
            retry({
                  count: this.config?.count ?? 0,
                  delay: this.config?.delay ?? 0,
                  resetOnSuccess: true
            }),
            catchError((error) => {
              const unhandledError = this.mapToUnhandledErrorInfo(
                command,
                error,
              );
              this.unhandledExceptionBus.publish(unhandledError);
              this._logger.error(
                `Command handler which execution was triggered by Saga has thrown an unhandled exception.`,
                error,
              );
              return of();
            }),
          ),
        ),
      )
      .subscribe();
```

### What is the motivation / use case for changing the behavior?

Adding this behavior, will allow users to set a retry strategy, for use cases, where for example a connection times out, or some other exception is thrown, that can be solved with a retry.

**Comment by MartinAndreev** [comment]
@kamilmysliwiec Hmm, but RxJS has a build retry, the problem is that because commands are executed with `defer` and a separate pipe, I cannot change the pipe, as the `retry` should happen before the `catchError`

**Comment by kamilmysliwiec** [comment]
You can still use RxJS retry with your own publisher. See the default implementation: https://github.dev/nestjs/cqrs/blob/a01a93255b89a97c2644794afb2f812af75892bb/src/helpers/default-command-pubsub.ts

**Comment by MartinAndreev** [comment]
Yeah, just figured out what you were pointing out. Thanks. I will wait for the new version, where you can pass the publishers as a configuration to simplify the setup.
