### ISSUE TITLE
Calling resolve(value) inside CommandHandler doesn't return value immediately

### ISSUE THREAD

**Issue by Silver96** [nestjs/cqrs#22]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report?
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior

__resolve(value)__ inside of a CommandHandler returns a value to the command caller after executing the Handler's body

## Expected behavior

As stated in the [recipe](https://docs.nestjs.com/recipes/cqrs) under the CommandsHandler example code, the __resolve(value)__ function should return a value to the caller and **then** continue executing where it left off. It is not clear if this is a bug or just misguiding documentation.

## Environment

<pre><code>
Nest version: 5.4.0
</code></pre>

**Comment by kamilmysliwiec** [comment]
It will change once #9 is merged.
