### ISSUE TITLE
How to raise an HTTP exception from a subsequent command that failed in a saga?

### ISSUE THREAD

**Issue by sebastiendan** [nestjs/cqrs#23]
Hi,

I created this issue on stackoverflow a while ago but didn't get much help.

https://stackoverflow.com/questions/53492063/how-to-raise-an-http-exception-from-a-subsequent-command-that-failed-in-a-saga-i

Any idea here?

**Comment by sebastiendan** [comment]
I replicated this issue on Nest main repo, as I'm not sure anyone is looking at issues here...

https://github.com/nestjs/nest/issues/1479

**Comment by kamilmysliwiec** [comment]
Hi @sebastiendan,
You could create a separate class which isolates a `Subject` instance inside. Once `UserProfile` has been successfully created, you can use this class to call `.next()` on the underlying `Subject` which in turn is being used before your `authService` call, like:

```typescript
const { authUser } = await this.authService.createAuthUser(createUserDto);
await this.notifierSubject.pipe(first());
```

also, you can bubble error up as well and then handle it through this extra Rx stream:
```typescript
await this.notifierSubject.pipe(
  first(),
  catchError(....),
)
```
However, I think that the main problem here is raising events from different application's instances in the distributed environment, correct? In this case, replace your `Subject` with some sort of pub/sub transporter (for instance Redis) to transfer events between different pods.

**Comment by sebastiendan** [comment]
@kamilmysliwiec Didn't think of using a Subject here... It's probably a very easy way to manage a transactions flow. However, I don't see the point now to use CQRS... I could just use a Subject instance, subscribed by all my transaction endpoints (User creation, User deletion, etc.) to keep the flow clean and sync. For instance, the Subject could hold a "state" object with an id for the current step and a payload for data identification transportation (User id is needed for User Profile creation).

The main problem isn't really dealing with multiple nodes on my app, it's really just about ordering and managing a set a transactions that need to react to each other.

I thought CQRS was the right answer for that challenge, but maybe I was wrong (plus it adds so much boilerplate...).

What do you think?

**Comment by kamilmysliwiec** [comment]
Alright, it seems that I misunderstood your issue. In this case, you can add two extra events that would indicate either success or failure of User Profile creation. Then, you could inject `EventBus` and subscribe to both events (using, let's say, `ofType()` + `merge()` operator). The failure event would mean that the whole transaction wasn't successfully completed (and then, simply `mergeMap` into error stream with an HTTP exception).

**Comment by sebastiendan** [comment]
Thanks for this solution. I'm currently working on a different project but I'll have to use soon the same logic so I'll give it a try.

I've got to say though that the idea of a global Subject instance + web sockets/sse to send real time status of transactions to clients is something that might be a more interesting, easier to develop and lighter solution for this topic (compared to CQRS).

Thanks @kamilmysliwiec ! And congrats for the awesome work on Nest. I'm glad it's getting greater attention every week (doing some promotion to big players here in Tokyo!).

**Comment by kamilmysliwiec** [comment]
Thank you @sebastiendan, fingers crossed 🤞 Keep me updated 🇯🇵
