### ISSUE TITLE
more complex project sample

### ISSUE THREAD

**Issue by mhcomp** [nestjs/cqrs#236]
## I'm submitting a...
<pre><code>[ ] Regression
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
Currently the package provides a [sample project](https://docs.nestjs.com/recipes/cqrs) which is fine but it doesn't provides some basic use cases e.g. creating a new hero Entity.

This might be simple but let's assume you would want to use a database (e.g. with TypeORM) and would come up with a database Entity

```ts
@Entity()
export class Hero extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  public id: string;
}
```

and your aggregate

```ts
export class Hero extends AggregateRoot {
  constructor(private readonly id: string) {
    super();
  }
}
```

To me the docs are lacking some information about some practises. The aggregate only comes up in the [events part](https://docs.nestjs.com/recipes/cqrs#events). Do you have to create two models? One for the database and one for the aggregate?

## Expected behavior
It would be nice to have a more complex sample project. Maybe a CRUD project (e.g. users or tasks) with a simple database integration.

Even more awesome would be a sample project using Event Sourcing. Currently Event Sourcing only comes up in the [summary](https://docs.nestjs.com/recipes/cqrs#summary)

## What is the motivation / use case for changing the behavior?
Currently there are many articles about the CQRS theory out there. But there are almost no samples on how to implement such architectures. The only project I found was this one

https://github.com/qas/examples-nodejs-cqrs-es-swagger

but if I understood correctly even this one is not a "real world project". It creates a new user in the [repository](https://github.com/qas/examples-nodejs-cqrs-es-swagger/blob/master/src/users/repository/user.repository.ts) by creating a new instance of the [aggregate](https://github.com/qas/examples-nodejs-cqrs-es-swagger/blob/master/src/users/models/user.model.ts) but it does not persist it somewhere.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/docs.nestjs.com/issues/957
