### ISSUE TITLE
Send events to Kafka / using event-sourcing pattern

### ISSUE THREAD

**Issue by DavidBM** [nestjs/cqrs#4]
Hi! 

In our team we are planning to use event-sourcing pattern with kafka. We really likes nest and it's CQRS module. We were wondering if there is a way to automatically launch the events to kafka. 

We can really implement it by ourselves, but we would like to ask if any of you use it with nest. It would be very nice to have some shared experiences :)

I guess that things like sagas may not be possible to implement with kafka. In any case, did you have any experience with event-sourcing and kafka? :D

**Comment by luqezman** [comment]
Im waiting for the same and also, I need controllers as consumers for specified redis server with options(retrys, timeouts) included.

**Comment by DavidBM** [comment]
Hi! 

We would like to implement it by ourselves. But, we are thinking that it can be a good opportunity to add a pull request to NestJS for supporting this pattern. We are a company in Berlin and I'm the CTO, if the people of Nest is ok and want to provide us hints and help, I can commit and developer for some months to this.

**Comment by Matonen** [comment]
What is status of this? No you need help? :)

**Comment by DavidBM** [comment]
Hi! 

Given the lack of answer, we decided to use nest only for the GraphQL part and use our own implementation of events and commands following DDD.

**Comment by johannesschobel** [comment]
what is the status of this? can we reopen this issue to get a kafka implementation for nestjs? @DavidBM 

all the best and happy new year

**Comment by DavidBM** [comment]
At the end we decided to use a better DDD approach and not to use a framework. We decided to use EventStore database instead of Kafka. If you want more details, ping me.

Happy new year!

**Comment by johannesschobel** [comment]
It would be awesome if you could provide me with more details on this @DavidBM . Which software products do you use?

All the best and happy new year,

**Comment by DavidBM** [comment]
https://eventstore.org/

We are developing our own abstraction over it, but the http client is easy to use. You have this library that makes easy to use in nodejs: https://www.npmjs.com/package/geteventstore-promise

**Comment by cingaldi** [comment]
Hello! which is the status of this, me and my team are planning to implement ES wih nestjs and kafka

**Comment by johannesschobel** [comment]
Dear @DavidBM ,
thanks for your answer.
Ok, so you're taking `eventstore` and adding your own `http wrapper` around it? Basically you're sending HTTP requests with the event-data to the eventstore? do you still save your models (as is; current state) in another "local" database (i.e., to speed up the performance when reading)? Can you share a repo to get more insights - that would be awesome!

**Comment by DavidBM** [comment]
Hi guys!

So, two companies past the original post, I just want to say, please, don't buy into the event sourcing hype! It may be a good idea for some domains, but definitely not for 95% of the cases. Event sourcing is good, but totally blows up the budget for many companies. 

I mean, you can use event sourcing, but be ready to pay 3 times the development cost.

Tools and patters are not streamlined at all, managing events can be really painful if you don't know what you are doing, projections and sagas ([processes, actually a saga is what reverts a process!!](https://stackoverflow.com/questions/15528015/what-is-the-difference-between-a-saga-a-process-manager-and-a-document-based-ap#15764667)]) can be very painful and a source of bugs if you don't know about them in deep.

And in general, you are undoing many abstractions the database is giving you for "free". If you have a normal web service and need logs in some places, just add an audit log or use a framework that gives it to you already done.

Also, please, if you really want to do event sourcing, don't use a framework like this one. Many concepts need to be updated and adapted to be fully event sourcing and just having a half event sourcing will create problems.

If you guys really really want to go for it, please, read this book first to have an summary of the problems you may face: https://leanpub.com/esversioning/read
