### ISSUE TITLE
Could not catch repository/service Exception

### ISSUE THREAD

**Issue by johnico** [nestjs/cqrs#473]
<pre><code>
[ ] Regression 
[X ] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

I could not catch an exception that throws in the repository level 
should I catch it? 

should I add try and catch in the command level? 

let's say I would like to send "failedEvent" and in this event publish a message to Queue, how can I do that? 

I tried to wrap the model, the event, and sags with try/catch

repository code:

```
  async create(createDto: CreateDto): Promise<Model> {
    throw new Error('tetse'); // throwing error
    const db = new this.model(createAuditDto);
    const res = await db.save();
    return new Model(res._id);
  }
```

command:

```
    const { dto } = command;
    const modelUpdate = this.publisher.mergeObjectContext(
      await this.repository.create(dto)
    );
    modelUpdate.save();
    modelUpdate.commit();
```

## Expected behavior
will be able to catch and handle an exception 

thanks

**Comment by Sikora00** [comment]
@johnico yes, you should wrap it in the try-catch block. You can do this in the command handler or you can wrap `this.commandBus.execute`. Depends on you. 
Btw as I know StackOverflow and Discord are better places for questions. Issues are used for bugs or feature requests.
