### ISSUE TITLE
Commands and Events do not work when emitted while NestJS is bootstrapping

### ISSUE THREAD

**Issue by rbutera** [nestjs/cqrs#489]
## Current behavior

Command Handlers and CommandBus do not work when commands are emitted during NestJS bootstrap (using `onApplicationBootstrap` method.

## Expected behavior

Command Handlers and CommandBus should behave as normal when commands are emitted during NestJS bootstrap (using `onApplicationBootstrap` method, or commands should be queued for execution once bootstrapping concludes.

## What is the motivation / use case for changing the behavior?

We want to issue some commands when our NestJS application initializes but unfortunately this does not work.

## Environment

Nest version: 7.0.1

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.
