### ISSUE TITLE
Support for transactions

### ISSUE THREAD

**Issue by pdeszynski** [nestjs/cqrs#5]
Hello,

It's more like a question than issue, but I could not find any info about this: does CQRS module (or core Nest.js) supports transactions with TypeORM? I didn't see any examples with transactions and I'm not sure if it is possible to make any further queries in `EventHandler` under the same transaction as in the command's `execute` method if any was started.

Secondary: does command run in transaction automatically or is it even possible to do it this way? In examples I saw an example with `PhotoService`, would it be possible to run it under transaction like:

```ts
@Component()
export class PhotoService {
  constructor(
    @Inject('PhotoRepositoryToken') private readonly photoRepository: Repository<Photo>) {}

  @Transaction()
  async findAll(): Promise<Photo[]> {
    // normally using you need to get the EntityManager as a parameter and request a repository from it
// and `this.photoRepository` cannot be used as it's outside of transaction scope
    return await this.photoRepository.find();
  }
}
```

**Comment by hugoblanc** [comment]
I'm quite interrested by the reason which lead you to clause this issue ?
