### ISSUE TITLE
Change `private` to `protected` for sub-classing?

### ISSUE THREAD

**Issue by RobertLowe** [nestjs/cqrs#735]
https://github.com/nestjs/cqrs/blob/1038a48d530ec46bf621fdbb3458ec9795d06a1c/src/cqrs.module.ts#L16-L19

@kamilmysliwiec what are your thoughts on changing these private properties to `protected` so they can be accessed from sub-classing (for custom CQRS modules)?

**Comment by kamilmysliwiec** [comment]
Sounds good to me, although, I think that if someone needs more complex CQRS implementation (with custom bus etc.), forking this package and just using it as a _base_ would have been better.
