### ISSUE TITLE
Distinguish between events with the same name

### ISSUE THREAD

**Issue by Sikora00** [nestjs/cqrs#790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Similar to #787 , but for events, their handlers don't overwrite. When we have two events with the same name and each of them has its own handlers then when any of them is published all of those handlers will be executed. This should not happen, as the coincidence of names can be random and they can mean different things, and they can also have different properties.

### Minimum reproduction code

soon

### Expected behavior

Only handlers registered for the specific class should be executed.

### Package version

8.0.0

### NestJS version

8.1.1

### Node.js version

16.11.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

Proposal https://github.com/nestjs-architects/cqrs/commit/83678dc3ad40fa712f48bd26ec521fb3f79d3b00

**Comment by ngoc199** [comment]
This bug has driven me crazy when applying CQRS with DDD. I have struggled the whole day and changing the class name works 😂.

How is the progress of fixing this bug? Can I do anything to help?

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue @Sikora00?

**Comment by Sikora00** [comment]
Sure, I already have something prepared
