### ISSUE TITLE
Strict mode

### ISSUE THREAD

**Issue by Sikora00** [nestjs/cqrs#792]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

one rabbi will say yes another rabbi will say no

### Describe the solution you'd like

Add `strict: true` and set `noImplicitAny` to true in the tsconfig

### What is the motivation / use case for changing the behavior?

It is for the library development experience.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/cqrs/pull/1861
