### ISSUE TITLE
Number of events being published grows with sub to EventBus in saga

### ISSUE THREAD

**Issue by jsonberry** [nestjs/cqrs#82]
## I'm submitting a...
<pre><code>
[x] Bug report
</code></pre>

## Current behavior
When subscribed to the `EventBus` in a flattening operator (`mergeMap`) in a `@Saga`, an `AggregateRoot` is publishing all old events as well as a new one for each subsequent `Command` being executed.

If I do a `take(1)` off of the `EventBus` this stop occurring. 

## Expected behavior
Only one event should be published at a time.

## Minimal reproduction of the problem with instructions
```typescript
@CommandHandler(DoThing)
export class DoThingHandler implements ICommandHandler<DoThing> {
  constructor(private someData: SomeDataAccessService) {}

  async execute(command: DoThing) {
    const model = this.someData.connectToWriteModel();
    await model.create(command.dto);
    model.commit();
  }
}
```
```typescript
import { SomeWriteModel } from './some-write.model';

@Injectable()
export class SomeDataAccessService {
  constructor(
    @InjectModel('SomeModel')
    private readonly someModel: Model<SomeDocument>,
    private readonly publisher: EventPublisher,
  ) {}

  connectToWriteModel() {
    return this.publisher.mergeObjectContext(
      new SomeWriteModel(this.someModel),
    );
  }
}
```
```typescript
export class SomeWriteModel extends AggregateRoot {
  constructor(
    private readonly doc: Model<CompanyDocument>,
  ) {
    super();
  }

  async create(dto: SomeDto) {
    let someDoc: SomeDocument;

    try {
      someDoc = await this.doc.findOne({ name: dto.name });
      if (someDoc) {
        // on every subsequent DoThing command
        // this block is only run once
        // but the event itself keeps adding +1
        // first time through: 1 SomeDocCreated, second time 2 will be published at the same time, then 3...
        this.apply(
          new SomeDocCreated(someDoc.name, someDoc._id.toString()),
        );

        return; 
      }
    }

   //.. etc
  }
}
```
```typescript
// SomeSaga

@Injectable()
export class SomeFeatureSagas {
  @Saga()
  someBigSaga$ = (
    events$: Observable<SomeBigSagaKickedOff>,
  ): Observable<DoMoreThings> =>
    events$.pipe(
      ofType(SomeBigSagaKickedOff),
      tap(s => this.commandBus.execute(new DoSomethingElse(s.foo))),
      mergeMap(s =>
        this.eventBus.pipe(
          filter<SomeDocCreated>(
            c =>
              c instanceof SomeDocCreated &&
              s.foo === c.foo,
          ),
         // take(1), <---- with a take(1), the behavior stops, without this many events are published
          map(
            c =>
              new DoMoreThings(),
          ),
        ),
      ),
    );

  constructor(readonly commandBus: CommandBus, readonly eventBus: EventBus) {}
}
```

## What is the motivation / use case for changing the behavior?
This just seems like an unexpected behavior, but there's probably more going on that I anticipate.

## Environment

<pre><code>
Nest version: 6.0.4
CQRS Module version: 6.0.0

**Comment by kamilmysliwiec** [comment]
Inside your `SomeWriteModel.create` method, I'd suggest checking your array of pending events (`this.getUncommittedEvents()` - this method is inherited from `AgreggateRoot`). If this array is empty, your saga logic is probably wrong. Otherwise, `commit()` works unexpectedly (doesn't clean the array after publishing events).

**Comment by jsonberry** [comment]
Ah yes @kamilmysliwiec my bad, this was all simply due to using a `mergeMap` and returning a hot observable.

This was just an Rx oversight on my part, thank you for taking the time to respond.

**Comment by mark-beeby** [comment]
@jsonberry did you have any hints on returning a cold observable? New to Rx here and struggling with the same problems. 
Cheers!

**Comment by jsonberry** [comment]
@mark-beeby If you are pulling in the `eventBus` into a Saga, just like I had in these examples, you'll need to use something like a `take(1)`. 

This is because that `Observable`, the one that's being returned inside the `mergeMap`, needs to `complete`, and if you return a `hot` Observable (like a `Subject`) it won't complete. There are some nuances there, but I'm just trying to get straight to the point :)

If you don't "complete", every time the Saga runs, a new subscription to the `eventBus` is created and is _added_ to any previous times the Saga ran, thus you get multiple events. When you `take(1)`, it'll close the subscription on the `eventBus` and you won't pile up with events you aren't expecting.

`cold` Observables, like `of('foo')` or `from(apiCall)` would complete automatically thus bypassing the "additional" and unnecessary subscriptions.
