### ISSUE TITLE
Command/query publisher is never called

### ISSUE THREAD

**Issue by bpawel10** [nestjs/cqrs#853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi,

I wanted to use custom publisher for commands, events and queries, but it doesn't work. If I connect my own publisher in `onModuleInit` method `this.command$.publisher = this.commandPublisher;` and then in a controller call `this.commandBus.execute(...)`, my publisher won't be called, because this publisher is never called in the command bus class. To make it work, I have to manually call `this.commandBus.publisher.publish(...)`.

### Minimum reproduction code

https://github.com/nestjs/cqrs/blob/master/src/command-bus.ts

### Expected behavior

I think we should move these two lines 
```
this.subject$.next(command);
return handler.execute(command);
```
from command bus `execute` method to default publisher and instead add `this._publisher.publish(...)` there. This way it would work fine for both default and custom publisher.

And the same applies to query bus.

### Package version

8.0.1

### NestJS version

8.2.3

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
