### ISSUE TITLE
Distributed Systems: Sagas & Location Transparency

### ISSUE THREAD

**Issue by StevenLangbroek** [nestjs/cqrs#905]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I've noticed a distinct difference in how NestJS treats Sagas, as opposed to how distributed systems engineers treat Sagas. While some things are the same, a big thing I cannot really find documented is the idea of "compensating transactions". Conversely, while the current module certainly implements location transparency within a single NestJS app, I have been unable to find any material on distributed location transparency the way that, for example, Axon Server & Axon Framework work together.

Is there interest in exploring this further? If so, we'd love to contribute. We (SmartRecruiters) operate some 300 microservices across different cloud providers, and have over the last couple of years added a few NestJS services. I'm keen to offer it as a first-class stack, which means that there are capabilities that we'd need to start offering...

### Describe the solution you'd like

It's hard to say exactly, but I think there is a rich catalog of prior art, research, and potentially open-source components that could be leveraged. While I certainly can't speak to its feasibility without digging in further, the CQRS module could take transports or strategies for different aspects of CQRS, defaulting to a "local" strategy for example. 

### What is the motivation / use case for changing the behavior?

The reason I think this could be beneficial is because in long-lived distributed systems, having infrastructure that allows you to more freely move logic between services provides your organization with a lot more agility to adjust to shifting realities; from reorgs to changes in traffic patterns. Furthermore, it seems the CQRS module uses the ubiquitous language of distributed systems "incorrectly" (sorry, I know this sounds dickish, it's not how I mean it), which can lead to confusion or disillusionment when evaluating NestJS among enterprise & distributed systems architects.

**Comment by kamilmysliwiec** [comment]
Check out this response @StevenLangbroek https://github.com/nestjs/cqrs/issues/164#issuecomment-559954585
